### ISSUE TITLE
Standardize Hidden Files

### ISSUE THREAD

**Issue by oeed** [oeed/CraftOS-Standards#22]
Standardising the files that should be ignored/hidden might also be useful.

For example, all files with the '.' prefix are hidden/ignored as well as things like _Desktop.ini_ (we'd need a standard list).

**Comment by lxndio** [comment]
Starting to work on this.

**Comment by lxndio** [comment]
Can be closed. See #27.

**Comment by viluon** [comment]
@lxndio use "Closes X" in your PR to close this issue automagically after merging.

**Comment by viluon** [comment]
I won't label this as accepted since #27 wasn't closed/merged yet.

**Comment by oeed** [comment]
I see where you are coming from, although the concept has been accepted, the PR and issue are two separate things.

It's your decision though, I'm happy with either approach as long as we're consistent :smile:

**Comment by viluon** [comment]
#27 was now closed, there's no need to standardize hidden files (separately from an OS standard family) (see my comment on #27). Feel free to reopen if you want to discuss this in greater detail. Labelling as 'rejected' for now.

Also, please don't close issues that are supposed to be solved by a PR @oeed, just use 'Closes #X' in the PR and it'll close automagically after merging, or stay open otherwise (which is what we want!).
