### ISSUE TITLE
MIME Type-based Repository Structure

### ISSUE THREAD

**Issue by ghost** [oeed/CraftOS-Standards#46]
to prevent problems like where to put file type documents in this documentation, the files could be arranged by mime-types e.g.

`text/plain`
would be
`CraftOS-Stantards/File-Types/text/plain.md`
instead of
`CraftOS-Stantards/File-Types/Plain-Text.md` (or whatever it currently is)

**Comment by viluon** [comment]
`meta`: I edited your message to use proper '`' characters

This is an interesting idea, to say the least. I don't know how well it'd work, given that we have just a small amount of standards at the moment, and searching through them is fairly easy. I would prefer the current categorized system (if we were to switch to this, categories would probably be dropped, because for some MIMEs you can't guess the category just from the type), but searching with MIME types would certainly be a great feature. What do you think of this @oeed ?

**Comment by ghost** [comment]
look at my fork @viluon , I already did something similar for the protocols, there are no folders, because protocolIDs are single words, but I also made a List with Links and some Information in a README.md

**Comment by viluon** [comment]
Pardon me @justsomeoneelseagain, but that is not a great idea. You should have created another branch. We cannot merge #44 if it contains more changes to the repository than just the Rednet docs, because that would mess things up. You should split your fork into multiple branches and PR each one separately, if you'd like to propose changes to oeed/CraftOS-Standards.

Otherwise, I really like how you've done the [README](https://github.com/justsomeoneelseagain/CraftOS-Standards/blob/master/Communication-Protocols/README.md) (**EDIT**: I mean the table with known standards, as well as the template link. Contributing should be outlined elsewhere (i.e. in the `tutorial` guide), because the whole repository shares the guidelines), and the idea of a template for every category (TEMPLATE.md) is awesome, I think we should adopt that @oeed.

**Comment by ghost** [comment]
ok, so then i´ll going to split it up

**Comment by ghost** [comment]
Maybe for every category a README.md and a TEMPLATE.md and files are named and sorted with an identifier (like MIME-Type or protocol-ID) in the Readme File a Table which listes all standards of the repository with identifier, name and a description and at the bottom of the readme file a link to the template file

**Comment by ghost** [comment]
I made Pull Request #48

**Comment by ghost** [comment]
It´s already merged.
